#!/usr/bin/env node
// Stage 6 — lint the emitted plan.
//
// Three jobs:
//   1. structure  — the 16 required sections of BACKEND-PLAN.md exist
//   2. sourcing   — content sections cite REQ-### / SCR-### / node ids
//   3. substance  — the A1..A12 register from references/anti-patterns.md,
//                   plus env names checked against the platform contract
//
// Headings may be in any language (the plan is written in the language of the
// spec), so structure is matched by the marker comments the template carries —
// `<!-- section: data-model -->` — falling back to EN/RU heading keywords.
import { existsSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { args, err, fail, info, ok, paths, read, style, warn } from "./lib/plan.mjs";

const a = args();
if (a.help) {
	info(
		[
			"Usage: node plan-lint.mjs [--strict] [--mode api|bot|both]",
			"",
			"  --strict   treat warnings as failures",
			"  --mode     override the mode from plan.json",
			"",
			"Lints out/ and design/ against references/anti-patterns.md.",
			"",
			"Suppress a rule on the line before it with:",
			"  <!-- lint-ignore A6: single-tenant internal tool, origin is fixed -->",
		].join("\n"),
	);
	process.exit(0);
}

const plan = existsSync(paths.plan) ? JSON.parse(read(paths.plan)) : {};
const mode = a.mode ?? plan.mode ?? "both";

let failures = 0;
let warnings = 0;
const seen = new Set();

function problem(level, rule, where, msg, fix) {
	const key = rule + where + msg;
	if (seen.has(key)) return;
	seen.add(key);
	if (level === "fail") {
		failures++;
		err(style.bold(rule) + "  " + where);
	} else {
		warnings++;
		warn(style.bold(rule) + "  " + where);
	}
	info("       " + msg);
	if (fix) info(style.dim("       fix: " + fix));
}

// ---- 1. structure -------------------------------------------------------

// [id, heading keywords (en/ru), needs citations, minimum words]
// Analytics and traceability are deliberately short: one points at
// docs/analytics.md, the other is generated by coverage-report.mjs.
const SECTIONS = [
	["summary", ["summary", "резюме", "кратко", "обзор"], false],
	["sources", ["sources", "источник"], false],
	["open-questions", ["open question", "открыт", "вопрос"], false],
	["domain-model", ["domain model", "доменн", "домен"], true],
	["data-model", ["data model", "модель данных", "схема данных", "схема бд"], true],
	["api-contract", ["api contract", "api", "эндпоинт", "контракт api"], true],
	["bot-contract", ["bot contract", "бот", "команд"], true],
	["concurrency", ["concurrency", "конкурент", "гонк", "race"], true],
	["background", ["background", "фонов", "джоб", "задач", "schedule"], true],
	["configuration", ["configuration", "конфиг", "переменны"], false],
	["observability", ["observability", "наблюдаем", "телеметри", "monitoring"], false],
	["analytics", ["analytics", "аналитик"], true, 4],
	["scaling", ["scaling", "масштабир", "нагрузк"], false],
	["platform", ["platform", "платформ", "деплой", "deploy"], false],
	["decisions", ["decision", "решени", "adr"], false, 8],
	["traceability", ["traceab", "трассир", "покрыти", "матрица"], false, 4],
];

const planDoc = read(paths.planDoc);
if (!planDoc)
	fail(
		"out/BACKEND-PLAN.md does not exist.\n" +
			"Stage 5 has not run. Sections and formats: references/deliverables.md.",
	);

/**
 * Slice the document by headings, tagging each with a section id.
 *
 * A marker comment conventionally sits on the line ABOVE its heading, which
 * puts it textually inside the previous section — so markers are associated
 * with the next heading within three lines, and only then with the enclosing one.
 */
function splitSections(md) {
	const lines = md.split("\n");
	const heads = [];
	lines.forEach((line, i) => {
		if (/^#{1,3}\s+\S/.test(line)) heads.push({ line: i, text: line.replace(/^#+\s*/, "") });
	});
	const markers = new Map();
	lines.forEach((line, i) => {
		const m = line.match(/<!--\s*section:\s*([a-z-]+)\s*-->/i);
		if (!m) return;
		const next = heads.find((h) => h.line >= i && h.line - i <= 3);
		const enclosing = [...heads].reverse().find((h) => h.line <= i);
		const target = next ?? enclosing;
		if (target) markers.set(target.line, m[1].toLowerCase());
	});
	const out = [];
	heads.forEach((h, i) => {
		const start = h.line;
		const end = i + 1 < heads.length ? heads[i + 1].line : lines.length;
		const body = lines.slice(start, end).join("\n");
		const marker = markers.get(h.line);
		const lower = h.text.toLowerCase();
		// The document title is not a section.
		const isTitle = i === 0 && /^#\s/.test(lines[h.line]);
		const guessed =
			marker ??
			(isTitle
				? null
				: (SECTIONS.find(([, keys]) => keys.some((k) => lower.includes(k)))?.[0] ?? null));
		out.push({ id: guessed, heading: h.text, start, end, body });
	});
	return out;
}

const docSections = splitSections(planDoc);
const present = new Map();
for (const s of docSections) if (s.id && !present.has(s.id)) present.set(s.id, s);

info("");
info(style.bold("plan-lint") + "  " + style.dim(paths.root + "  mode=" + mode));
info("");

for (const [id, keys, needsCitation, min = 12] of SECTIONS) {
	if (id === "api-contract" && mode === "bot") continue;
	if (id === "bot-contract" && mode === "api") continue;
	const section = present.get(id);
	if (!section) {
		problem(
			"fail",
			"DOC-SECTION",
			"BACKEND-PLAN.md",
			"missing required section: " + id,
			"add a heading containing one of [" +
				keys.slice(0, 3).join(", ") +
				"] or the marker <!-- section: " +
				id +
				" -->",
		);
		continue;
	}
	const text = section.body
		.replace(/<!--[\s\S]*?-->/g, "")
		.replace(/^#+.*$/m, "")
		.trim();
	const words = text.split(/\s+/).filter(Boolean).length;
	const soft = id === "open-questions" || id === "traceability";
	// Below the minimum is empty. Below 30 is thin — worth a look, not a blocker.
	if (words < min)
		problem(
			soft ? "warn" : "fail",
			"DOC-EMPTY",
			"BACKEND-PLAN.md  " + section.heading,
			"section is " + words + " words — effectively empty",
			id === "open-questions"
				? "an empty open-questions section usually means somebody guessed"
				: id === "traceability"
					? "run coverage-report.mjs and paste out/traceability.md in here"
					: "references/deliverables.md lists what belongs here",
		);
	else if (words < 30 && min === 12)
		problem(
			"warn",
			"DOC-THIN",
			"BACKEND-PLAN.md  " + section.heading,
			"section is " + words + " words — thin for what it has to carry",
			"references/deliverables.md lists what belongs here",
		);
	if (needsCitation && !/REQ-\d|SCR-\d|H-\d|\d+:\d+/.test(section.body))
		problem(
			"fail",
			"DOC-CITE",
			"BACKEND-PLAN.md  " + section.heading,
			"no citations — every factual claim carries a REQ-###, SCR-### or Figma node id",
			"a section with no citations is a section somebody invented",
		);
}

const conc = present.get("concurrency");
if (conc && !/H-\d/.test(conc.body))
	problem(
		"fail",
		"DOC-HOTSPOT",
		"BACKEND-PLAN.md  " + conc.heading,
		"the concurrency section names no H-### entry",
		"carry design/hotspots.md into the plan as a table",
	);

if (!/\/health\b/.test(planDoc))
	problem(
		"warn",
		"PLATFORM-HEALTH",
		"BACKEND-PLAN.md",
		"no GET /health mentioned — the pipeline sets HTTP_HEALTH_CHECK: /health",
		"it must exist, stay cheap, touch no database, and be excluded from tracing",
	);

if (/NODE_TLS_REJECT_UNAUTHORIZED/.test(planDoc)) {
	const line = planDoc.split("\n").find((l) => l.includes("NODE_TLS_REJECT_UNAUTHORIZED")) ?? "";
	if (/anti-?pattern|антипаттерн|убрать|remove|should not|недопустим/i.test(line))
		problem(
			"warn",
			"PLATFORM-TLS",
			"BACKEND-PLAN.md",
			"NODE_TLS_REJECT_UNAUTHORIZED=0 is a production requirement here, not a finding",
			"state the process-wide consequence once, then recommend narrowing it to the migration step — references/platform-contract.md",
		);
}

// ---- 2. env names -------------------------------------------------------

const PLATFORM_ENV = new Set(
	(
		"DATABASE_URL REDIS_HOST S3_ENDPOINT S3_INTERNAL_ENDPOINT S3_ACCESS S3_SECRET " +
		"S3_BUCKET S3_REGION PORT PUBLIC_DOMAIN API_URL NODE_ENV USE_SSL " +
		"BOT_TOKEN WEBHOOK_SECRET OPENAI_API_TOKEN SENTRY_DSN ADMIN_EMAIL ADMIN_PASSWORD " +
		"ADMIN_COOKIE_SECRET FRONTEND_URL LOCK_STORE POSTHOG_API_KEY POSTHOG_HOST " +
		"OPENAPI_PATH OWNER_IDS TIMEZONE STATIC_URL " +
		"OTEL_SERVICE_NAME OTEL_EXPORTER_OTLP_ENDPOINT NODE_TLS_REJECT_UNAUTHORIZED " +
		"DEPLOY_FROM HTTP_ENABLED HTTP_PORT S_PORT HTTP_HEALTH_CHECK HTTP_CERT HTTP_SUBDOMAIN " +
		"POSTGRES_ENABLED REDIS_ENABLED MINIO_ENABLED MINIO_BUCKETS SECRETS"
	).split(/\s+/),
);

const WRONG_ENV = {
	DB_URL: "DATABASE_URL",
	DB_HOST: "DATABASE_URL",
	DATABASE_URI: "DATABASE_URL",
	POSTGRES_URL: "DATABASE_URL",
	POSTGRES_DSN: "DATABASE_URL",
	PG_URL: "DATABASE_URL",
	REDIS_URL: "REDIS_HOST",
	REDIS_DSN: "REDIS_HOST",
	S3_ACCESS_KEY: "S3_ACCESS",
	S3_SECRET_KEY: "S3_SECRET",
	AWS_ACCESS_KEY_ID: "S3_ACCESS",
	AWS_SECRET_ACCESS_KEY: "S3_SECRET",
	TELEGRAM_BOT_TOKEN: "BOT_TOKEN",
	TELEGRAM_TOKEN: "BOT_TOKEN",
	TG_TOKEN: "BOT_TOKEN",
	APP_PORT: "PORT",
	SERVER_PORT: "PORT",
	HTTP_SERVER_PORT: "PORT",
	BASE_URL: "API_URL",
	SELF_URL: "API_URL",
	SENTRY_URL: "SENTRY_DSN",
	CORS_ORIGIN: "FRONTEND_URL",
};

for (const [wrong, right] of Object.entries(WRONG_ENV)) {
	const re = new RegExp("(?<![A-Z0-9_])" + wrong + "(?![A-Z0-9_])");
	if (re.test(planDoc))
		problem(
			"fail",
			"ENV-NAME",
			"BACKEND-PLAN.md",
			wrong + " is not what the platform injects — it sets " + right,
			"a plan that reads beautifully and cannot deploy is worse than no plan — references/platform-contract.md",
		);
}

// Unknown names, but only where the text is actually talking about configuration.
const cfg = present.get("configuration");
const envLines = planDoc
	.split("\n")
	.filter((l) => /env\.get\(|process\.env\.|^\|\s*`?[A-Z][A-Z0-9_]/.test(l));
const envScope = (cfg?.body ?? "") + "\n" + envLines.join("\n");
const SKIP_TOKEN =
	/^(REQ|SCR|ADR|TODO|NOTE|FIXME|GET|POST|PUT|PATCH|DELETE|ON_CONFLICT|SKIP_LOCKED|FOR_UPDATE|READ_COMMITTED|REPEATABLE_READ|SERIALIZABLE|READY_FOR_DEV|NOT_NULL|PRIMARY_KEY)/;
const unknown = new Set();
for (const m of envScope.matchAll(
	/(?<![A-Za-z0-9_])([A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+)(?![A-Za-z0-9_])/g,
)) {
	const name = m[1];
	if (PLATFORM_ENV.has(name) || WRONG_ENV[name] || SKIP_TOKEN.test(name)) continue;
	unknown.add(name);
}
if (unknown.size) {
	const declared =
		/new to ci|новая переменная|новые переменные|добавить в ci|add to ci|new application variable/i.test(
			cfg?.body ?? "",
		);
	problem(
		declared ? "warn" : "fail",
		"ENV-NEW",
		"BACKEND-PLAN.md  configuration",
		(declared ? "new" : "undeclared new") +
			" application variable(s): " +
			[...unknown].sort().join(", "),
		declared
			? "each one is a real CI task with a lead time — keep them in the backlog"
			: "mark them explicitly as new to CI, and add a backlog item per sealed secret",
	);
}

// ---- 3. anti-patterns ---------------------------------------------------

// A quote character class covering ' " and template literals. The backtick is
// built from its code point so this file stays safe to paste anywhere.
const Q = "[\"'" + String.fromCharCode(96) + "]";

const RULES = [
	{
		id: "A1",
		level: "fail",
		re: /\.set\(\s*\{[^}]*\b(balance|stock|count|amount|quantity|остат\w*)\b[^}]*[-+]\s*\w/i,
		msg: "read-modify-write on a numeric column",
		fix: "UPDATE ... SET col = col - :n WHERE col >= :n RETURNING — the predicate belongs inside the statement",
	},
	{
		id: "A2",
		level: "fail",
		re: /\.acquire\(\s*\)/,
		msg: "acquire() with no retry timeout — the default is Infinity, so contention exhausts the pool and the symptom is a hung service",
		fix: "acquire({ retry: { attempts, delay, timeout } }), or runImmediately() answering 409",
	},
	{
		id: "A2",
		level: "warn",
		re: /createLock\(\s*[^,)]+\)/,
		msg: "createLock() with no explicit TTL — the 30s default is shorter than many real critical sections",
		fix: "createLock(key, '2m'), sized to the worst case",
	},
	{
		id: "A3",
		level: "fail",
		re: /:(bot)?[Tt]oken\b|:secret\b|\/webhook\/:[a-z]/,
		msg: "a credential in the URL path — paths are logged by nginx, the ingress, the APM and every trace span",
		fix: "a header (X-Telegram-Bot-Api-Secret-Token) compared in constant time, on a fixed path",
	},
	{
		id: "A4",
		level: "fail",
		re: /setInterval\s*\(|lastRunAt|\+\s*3\s*\*\s*60\s*\*\s*60|UTC\s*\+\s*3\b/i,
		msg: "home-made scheduler: every replica fires its own timer, the lastRunAt guard is itself a read-modify-write race, and a hand-rolled offset breaks on DST",
		fix: "taskora schedules (leader election, IANA timezone, missed-run policy) plus UNIQUE (job_name, scheduled_for)",
	},
	{
		id: "A5",
		level: "fail",
		re: /\bp-queue\b|new\s+PQueue|\bp-debounce\b|\bbullmq\b|\bnode-cron\b|\bagenda\b/i,
		msg: "durable work in an in-process queue, or a job library outside the stack — a deploy drops everything in flight, silently",
		fix: "taskora for anything that must survive a restart — references/jobs-taskora.md",
	},
	{
		id: "A6",
		level: "fail",
		re: /\bcors\(\s*\)|origin:\s*Q\*Q|origin:\s*true\b/,
		msg: "open CORS — any site can call this API from a victim browser with their credentials attached",
		fix: "an explicit origin list from FRONTEND_URL, with methods and headers enumerated",
	},
	{
		id: "A6",
		level: "warn",
		re: /origin[^\n]{0,40}\.(includes|endsWith|startsWith)\(/,
		msg: "origin matched by substring — evil-yourdomain.com passes",
		fix: "exact comparison against a parsed allow-list",
	},
	{
		id: "A7",
		level: "fail",
		re: /[A-Z_]*(SECRET|TOKEN|PASSWORD|API_KEY|DSN|PRIVATE_KEY)[A-Z_]*Q?\s*\)?\s*\.\s*default\s*\(/,
		msg: "a secret with a default — the service boots with a junk credential and the misconfiguration surfaces later, as missing data",
		fix: ".required(), or genuinely optional behind an explicit feature flag",
	},
	{
		id: "A8",
		level: "fail",
		re: /\.default\(\s*Q(-100\d{7,}|https?:\/\/(?!localhost|127\.)[^"'`]+|\d{9,})Q\s*\)/,
		msg: "a production identifier as a code default — a staging deploy missing the variable writes to production",
		fix: ".required() for anything naming a real resource",
	},
	{
		id: "A9",
		level: "fail",
		re: /(PUBLIC_DOMAIN|DOMAIN|HOST|URL)[^\n]{0,30}\.includes\(\s*Q(staging|prod|dev)/i,
		msg: "environment inferred from a hostname — renaming a host silently changes runtime behaviour and security posture",
		fix: "NODE_ENV, or an explicit APP_ENV",
	},
	{
		id: "A10",
		level: "fail",
		re: /setContext\(\s*\{[^}]*\b(headers|body|initData|cookies)\b|console\.log\(\s*(req|request|body)\b/i,
		msg: "personal data into the error tracker or the log — headers carry the auth token and init-data, bodies carry phone numbers",
		fix: "a redacted allow-list: route, user id, request id, error code, trace id — references/telemetry.md",
	},
	{
		id: "A11",
		level: "fail",
		re: /disabled:\s*(process\.env\.)?NODE_ENV\s*!==?\s*Qproduction/,
		msg: "analytics disabled outside production — staging is blind, so analytics bugs can only be found in production",
		fix: "a separate project key per environment — references/analytics.md",
	},
	{
		id: "A12",
		level: "fail",
		re: /sql\.raw\(\s*[^)]*(\+|$\{)/,
		msg: "sql.raw built by concatenation — SQL injection wearing a safe-looking costume",
		fix: "parameter binding, e.g. unnest($1::text[])",
	},
	{
		id: "A12",
		level: "fail",
		re: /\bas\s+any\b|additionalProperties:\s*true/,
		msg: "validation that validates nothing — a mass-assignment vector",
		fix: "strict schemas, no casts through any",
	},
	{
		id: "A12",
		level: "warn",
		re: /\blimit\b\s*[:=]\s*(t\.)?(Number|Numeric|Integer)\(\s*\)/,
		msg: "an unbounded limit on a list endpoint — a denial-of-service endpoint with good intentions",
		fix: "bound it in the schema (maximum: 100) and give it a default",
	},
	{
		id: "X1",
		level: "warn",
		re: /uncaughtException/,
		msg: "uncaughtException handler — make sure it reports, flushes, then exits",
		fix: "logging and continuing leaves the process in an undefined state",
	},
	{
		id: "X2",
		level: "warn",
		re: /401[^\n]{0,60}(ban|banned|блок|забанен)|(ban|banned|блок|забанен)[^\n]{0,60}401/i,
		msg: "401 for a banned user logs them out instead of telling them they are banned",
		fix: "401 = who are you, 403 = no, 409 = state conflict",
	},
	{
		id: "STACK",
		level: "fail",
		re: /\b(express|nestjs|fastify|prisma|typeorm|sequelize|mongoose|kafka|rabbitmq|микросервис\w*|microservices?)\b/i,
		msg: "a component outside the fixed stack",
		fix: "allowed only via an ADR stating what the stack could not do — see the stack table in SKILL.md",
	},
];

// Re-hydrate the quote class into every rule that needs it.
for (const rule of RULES) {
	if (rule.re.source.includes("Q"))
		rule.re = new RegExp(rule.re.source.replace(/Q/g, Q), rule.re.flags);
}

function collect(dir, acc = []) {
	if (!existsSync(dir)) return acc;
	for (const name of readdirSync(dir)) {
		const p = join(dir, name);
		if (statSync(p).isDirectory()) collect(p, acc);
		else if (/\.(md|ts|tsx|yaml|yml|sql)$/.test(name)) acc.push(p);
	}
	return acc;
}

const files = [...collect(paths.out), ...collect(paths.design)];
const adrCorpus = collect(paths.adr)
	.map((p) => read(p) ?? "")
	.join("\n")
	.toLowerCase();

/**
 * Fences introduced as counter-examples are quoted on purpose. Skip them, or
 * every plan that teaches a rule fails the rule it teaches.
 */
function negativeRanges(lines) {
	const ranges = [];
	let open = null;
	for (let i = 0; i < lines.length; i++) {
		if (!/^\s*```/.test(lines[i])) continue;
		if (open === null) {
			const before = lines
				.slice(Math.max(0, i - 4), i)
				.filter((l) => l.trim())
				.join(" ");
			open = {
				start: i,
				bad: /never|не так|антипаттерн|anti-?pattern|плохо|wrong|\bbad\b|нельзя|не делай|symptom|симптом|было:/i.test(
					before,
				),
			};
		} else {
			if (open.bad) ranges.push([open.start, i]);
			open = null;
		}
	}
	return ranges;
}

for (const file of files) {
	const text = read(file) ?? "";
	const lines = text.split("\n");
	const skip = negativeRanges(lines);
	const rel = relative(paths.root, file);

	lines.forEach((line, i) => {
		if (skip.some(([s, e]) => i >= s && i <= e)) return;
		const prev = lines[i - 1] ?? "";
		for (const rule of RULES) {
			const m = line.match(rule.re);
			if (!m) continue;
			const ignore = new RegExp("lint-ignore\\s+" + rule.id + "\\b");
			if (ignore.test(line) || ignore.test(prev)) continue;
			// A stack deviation argued in its own ADR is a decision, not a smell.
			if (rule.id === "STACK" && adrCorpus.includes(m[0].toLowerCase())) continue;
			problem(
				rule.level,
				rule.id,
				rel + ":" + (i + 1),
				rule.msg + "\n       " + style.dim(line.trim().slice(0, 90)),
				rule.fix,
			);
		}
	});

	// A11(a): capture() inside a transaction — a fence-level question, not a line-level one.
	text.split(/```/).forEach((fence, k) => {
		if (k % 2 === 0) return;
		if (/\.transaction\(/.test(fence) && /\bcapture\(|posthog\.[a-z]+\(/i.test(fence))
			problem(
				"warn",
				"A11",
				rel,
				"analytics captured inside a transaction — it reports rolled-back events and puts network latency inside the lock window",
				"capture after commit",
			);
	});
}

// ---- summary ------------------------------------------------------------

info("");
info(
	"  " + files.length + " file(s) linted, " + failures + " failing, " + warnings + " warning(s)",
);
info("");

if (failures) {
	err("Plan does not pass. Every rule id is explained in references/anti-patterns.md.");
	info("");
	process.exit(1);
}
if (warnings && a.strict) {
	err("--strict: warnings are failures.");
	info("");
	process.exit(1);
}
ok("Plan is clean.");
info("");
